title: "Varatharajan | Data Engineering & AI"
description: "Learning • Building • Sharing about Data Engineering, Cloud, and AI"
url: "https://vrajans.github.io"

# Enable Minimal Mistakes (required for GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# Author Info
author:
  name: "Varatharajan Subramanian"
  avatar: "/assets/profile.png"
  bio: "Data Engineering Manager | Cloud | AI | Architecting Data Solutions"
  location: "Dallas, TX"

# Output posts
collections:
  posts:
    output: true

# Default settings
defaults:
  - scope:
      path: ""
    values:
      layout: single
